### ISSUE TITLE
Python bindings fail to compile with python 3.6

### ISSUE THREAD

**Issue by wthrowe** [sxs-collaboration/spectre#1518]
Building with python 2.7 is successful.

```
[100%] Building CXX object src/DataStructures/Python/CMakeFiles/PyDataStructures.dir/Bindings.cpp.o
In file included from /usr/include/bits/types/stack_t.h:23:0,
                 from /usr/include/signal.h:303,
                 from /usr/include/python3.6m/pyfpe.h:129,
                 from /usr/include/python3.6m/Python.h:137,
                 from /usr/include/boost/python/detail/wrap_python.hpp:151,
                 from /usr/include/boost/python/detail/prefix.hpp:13,
                 from /usr/include/boost/python/args.hpp:8,
                 from /usr/include/boost/python.hpp:11,
                 from /home/wthrowe/spectre/src/DataStructures/Python/Bindings.cpp:4:
/home/wthrowe/spectre/src/DataStructures/Python/Bindings.cpp: In function ‘void init_module__DataStructures()’:
/home/wthrowe/spectre/src/DataStructures/Python/Bindings.cpp:32:3: error: return-statement with a value, in function returning 'void' [-fpermissive]
   import_array();
   ^
compilation terminated due to -Wfatal-errors.
```
LibraryVersions.txt:
```
CMake Version: 3.9.6
SpECTRE Version: 0.0.0
SpECTRE branch: build_without_python_bindings
SpECTRE hash: b67cc9a1c4a10d020ceb3de5c29ed41ab5016610
Hostname: ungoliant
Host system: Linux-4.14.83-gentoo
Host system version: 4.14.83-gentoo
Host system processor: x86_64
CMAKE_CXX_FLAGS: -fdiagnostics-color=always -frecord-gcc-switches -Wfatal-errors -ftemplate-backtrace-limit=0 -march=native -fPIC
CMAKE_CXX_LINK_FLAGS: 
CMAKE_CXX_FLAGS_DEBUG: -g
CMAKE_CXX_FLAGS_RELEASE: -O3 -DNDEBUG
CMAKE_C_FLAGS: -march=native -fPIC
CMAKE_C_LINK_FLAGS: 
CMAKE_C_FLAGS_DEBUG: -g
CMAKE_C_FLAGS_RELEASE: -O3 -DNDEBUG
CMAKE_Fortran_FLAGS: -march=native
CMAKE_Fortran_LINK_FLAGS: 
CMAKE_Fortran_FLAGS_DEBUG: -g
CMAKE_Fortran_FLAGS_RELEASE: -O3 -DNDEBUG -O3
CMAKE_EXE_LINKER_FLAGS: -march=native -no-pie
CMAKE_BUILD_TYPE: Debug
CMAKE_CXX_COMPILER: /usr/bin/g++-6.4.0
CMAKE_CXX_COMPILER_VERSION: 6.4.0
CMAKE_C_COMPILER: /usr/bin/gcc-6.4.0
CMAKE_C_COMPILER_VERSION: 6.4.0
CMAKE_Fortran_COMPILER: /usr/bin/gfortran
CMAKE_Fortran_COMPILER_VERSION: 6.4.0
Python Version: 3.6.5
Charm Version:  6.8.0
Charm SMP:  YES
BLAS_LIBRARIES:  /usr/lib64/blas/reference/libblas.so
Blaze Version:  3.2
Boost Version:  1.65.0
Catch Version:  2.5.0
Google Benchmark Found
GSL Version:  1.16
HDF5 Version:  1.8.18
jemalloc Version:  ..
LIBXSMM Version:  1.8.1
LAPACK_LIBRARIES:  /usr/lib64/lapack/reference/liblapack.so;/usr/lib64/blas/reference/libblas.so
NumPy Version:  1.14.5
SciPy Version:  0.19.1
```

**Comment by nilsdeppe** [comment]
Thanks for finding this @wthrowe! In terms of action items:

- [ ] Fix so that the current code compiles. We need to see how we deal with this elsewhere in the code, and what the correct way of dealing with it is. I think some of the `pypp` code should have to deal with this problem.
- [ ] We need to make sure we test more python envs on Travis to catch these issues before merging.
