### PR TITLE
Fix Boost version across CMake versions

### LINKED ISSUE #2644: develop does not compile with Boost 1.72
Presumably broken by #2636.

```
[ 18%] Building CXX object src/IO/CMakeFiles/IO.dir/H5/Helpers.cpp.o
In file included from /home/wthrowe/spectre/src/IO/H5/Helpers.cpp:13:
In file included from /home/wthrowe/spectre/src/DataStructures/BoostMultiArray.hpp:20:
In file included from /usr/include/boost/multi_array.hpp:29:
In file included from /usr/include/boost/multi_array/base.hpp:22:
In file included from /usr/include/boost/multi_array/extent_gen.hpp:18:
/usr/include/boost/multi_array/types.hpp:29:24: error: type alias redefinition with different types ('std::ptrdiff_t' (aka 'long') vs 'std::size_t' (aka 'unsigned long'))
typedef std::ptrdiff_t index;
                       ^
/home/wthrowe/spectre/src/DataStructures/BoostMultiArray.hpp:15:7: note: previous definition is here
using index = std::size_t;
      ^
1 error generated.
```

Examining the compiler invocation, the flag `-DBOOST_MULTI_ARRAY_TYPES_HPP` is being passed, which is the value for Boost 1.73.

From CMake output:
```
-- Found Boost: /usr/include (found suitable version "1.72.0", minimum required is "1.60.0") found components: program_options 
-- Boost include: /usr/include
-- Boost libraries: /usr/lib64/libboost_program_options-mt.so
```

LibraryVersions.txt
```
CMake Version: 3.17.4
SpECTRE Version: 2020.12.7
SpECTRE branch: develop
SpECTRE hash: v2020.12.07
Hostname: ungoliant
Host system: Linux-5.4.60-gentoo
Host system version: 5.4.60-gentoo
Host system processor: x86_64
CMAKE_CXX_FLAGS: -fPIC -fdiagnostics-color=always -ferror-limit=1 -ftemplate-backtrace-limit=0 -march=native
CMAKE_CXX_LINK_FLAGS:  -L/usr/lib64 -fuse-ld=gold
CMAKE_CXX_FLAGS_DEBUG: -g -DSPECTRE_DEBUG
CMAKE_CXX_FLAGS_RELEASE: -O3 -DNDEBUG
CMAKE_C_FLAGS: -fPIC -march=native
CMAKE_C_FLAGS_DEBUG: -g
CMAKE_C_FLAGS_RELEASE: -O3 -DNDEBUG
CMAKE_Fortran_FLAGS: -march=native
CMAKE_Fortran_FLAGS_DEBUG: -g
CMAKE_Fortran_FLAGS_RELEASE: -O3 -DNDEBUG -O3
CMAKE_EXE_LINKER_FLAGS: -march=native -no-pie
CMAKE_BUILD_TYPE: Debug
CMAKE_CXX_COMPILER: /usr/lib/llvm/10/bin/clang++-10
CMAKE_CXX_COMPILER_VERSION: 10.0.1
CMAKE_C_COMPILER: /usr/lib/llvm/10/bin/clang-10
CMAKE_C_COMPILER_VERSION: 10.0.1
CMAKE_Fortran_COMPILER: /usr/bin/gfortran
CMAKE_Fortran_COMPILER_VERSION: 7.5.0
Python Version: 3.7.9
```

### PR DESCRIPTION
**Pull request by nilsvu**
## Proposed changes

Fixes #2644

### Types of changes:

- [ ] Bugfix
- [ ] New feature
- [ ] Refactor

### Component:

- [ ] Code
- [ ] Documentation
- [ ] Build system
- [ ] Continuous integration

### Code review checklist

- [ ] The PR passes all checks, including unit tests and `clang-tidy`.
  For instructions on how to perform the CI checks locally refer to the [Dev
  guide on the Travis CI](https://spectre-code.org/travis_guide.html).
- [ ] The code is documented and the documentation renders correctly. Run
  `make doc` to generate the documentation locally into `BUILD_DIR/docs/html`.
  Then open `index.html`.
- [ ] The code follows the stylistic and code quality guidelines listed in the
  [code review guide](https://spectre-code.org/code_review_guide.html).

### CODE REVIEW

**Review by wthrowe — APPROVED** [review]
This works!  Thank you.

I'm not going to think too hard about why an unset variable was greater than or equal to 1.73.0.

**Review by nilsdeppe — APPROVED** [review]

**Review by geoffrey4444 — APPROVED** [review]
I ran into trouble on ocean, building latest develop as of 12/11/20 at 1:50PM PST, and cherry-picking this commit fixed it.

**Comment by nilsvu** [comment]
@wthrowe the `Boost_VERSION` variable would not be unset but hold the content of `boost/version.h`. I'm curious now, could you print the content of that file on your machine here?

**Comment by wthrowe** [comment]
(Assuming you meant version.hpp, since I don't have a .h)
```
//  Boost version.hpp configuration header file  ------------------------------//

//  (C) Copyright John maddock 1999. Distributed under the Boost
//  Software License, Version 1.0. (See accompanying file
//  LICENSE_1_0.txt or copy at http://www.boost.org/LICENSE_1_0.txt)

//  See http://www.boost.org/libs/config for documentation

#ifndef BOOST_VERSION_HPP
#define BOOST_VERSION_HPP

//
//  Caution: this is the only Boost header that is guaranteed
//  to change with every Boost release. Including this header
//  will cause a recompile every time a new Boost version is
//  used.
//
//  BOOST_VERSION % 100 is the patch level
//  BOOST_VERSION / 100 % 1000 is the minor version
//  BOOST_VERSION / 100000 is the major version

#define BOOST_VERSION 107200
//
//  BOOST_LIB_VERSION must be defined to be the same as BOOST_VERSION
//  but as a *string* in the form "x_y[_z]" where x is the major version
//  number, y is the minor version number, and z is the patch level if not 0.
//  This is used by <config/auto_link.hpp> to select which library version to link to.

#define BOOST_LIB_VERSION "1_72"

#endif
```
