### PR TITLE
Support Py2 and Py3 by switching to Pybind11

### LINKED ISSUE #1518: Python bindings fail to compile with python 3.6
Building with python 2.7 is successful.

```
[100%] Building CXX object src/DataStructures/Python/CMakeFiles/PyDataStructures.dir/Bindings.cpp.o
In file included from /usr/include/bits/types/stack_t.h:23:0,
                 from /usr/include/signal.h:303,
                 from /usr/include/python3.6m/pyfpe.h:129,
                 from /usr/include/python3.6m/Python.h:137,
                 from /usr/include/boost/python/detail/wrap_python.hpp:151,
                 from /usr/include/boost/python/detail/prefix.hpp:13,
                 from /usr/include/boost/python/args.hpp:8,
                 from /usr/include/boost/python.hpp:11,
                 from /home/wthrowe/spectre/src/DataStructures/Python/Bindings.cpp:4:
/home/wthrowe/spectre/src/DataStructures/Python/Bindings.cpp: In function ‘void init_module__DataStructures()’:
/home/wthrowe/spectre/src/DataStructures/Python/Bindings.cpp:32:3: error: return-statement with a value, in function returning 'void' [-fpermissive]
   import_array();
   ^
compilation terminated due to -Wfatal-errors.
```
LibraryVersions.txt:
```
CMake Version: 3.9.6
SpECTRE Version: 0.0.0
SpECTRE branch: build_without_python_bindings
SpECTRE hash: b67cc9a1c4a10d020ceb3de5c29ed41ab5016610
Hostname: ungoliant
Host system: Linux-4.14.83-gentoo
Host system version: 4.14.83-gentoo
Host system processor: x86_64
CMAKE_CXX_FLAGS: -fdiagnostics-color=always -frecord-gcc-switches -Wfatal-errors -ftemplate-backtrace-limit=0 -march=native -fPIC
CMAKE_CXX_LINK_FLAGS: 
CMAKE_CXX_FLAGS_DEBUG: -g
CMAKE_CXX_FLAGS_RELEASE: -O3 -DNDEBUG
CMAKE_C_FLAGS: -march=native -fPIC
CMAKE_C_LINK_FLAGS: 
CMAKE_C_FLAGS_DEBUG: -g
CMAKE_C_FLAGS_RELEASE: -O3 -DNDEBUG
CMAKE_Fortran_FLAGS: -march=native
CMAKE_Fortran_LINK_FLAGS: 
CMAKE_Fortran_FLAGS_DEBUG: -g
CMAKE_Fortran_FLAGS_RELEASE: -O3 -DNDEBUG -O3
CMAKE_EXE_LINKER_FLAGS: -march=native -no-pie
CMAKE_BUILD_TYPE: Debug
CMAKE_CXX_COMPILER: /usr/bin/g++-6.4.0
CMAKE_CXX_COMPILER_VERSION: 6.4.0
CMAKE_C_COMPILER: /usr/bin/gcc-6.4.0
CMAKE_C_COMPILER_VERSION: 6.4.0
CMAKE_Fortran_COMPILER: /usr/bin/gfortran
CMAKE_Fortran_COMPILER_VERSION: 6.4.0
Python Version: 3.6.5
Charm Version:  6.8.0
Charm SMP:  YES
BLAS_LIBRARIES:  /usr/lib64/blas/reference/libblas.so
Blaze Version:  3.2
Boost Version:  1.65.0
Catch Version:  2.5.0
Google Benchmark Found
GSL Version:  1.16
HDF5 Version:  1.8.18
jemalloc Version:  ..
LIBXSMM Version:  1.8.1
LAPACK_LIBRARIES:  /usr/lib64/lapack/reference/liblapack.so;/usr/lib64/blas/reference/libblas.so
NumPy Version:  1.14.5
SciPy Version:  0.19.1
```

### LINKED ISSUE #1829: Boost.Python or Pybind11
# Feature request:

This issue is to consider [Pybind11](https://pybind11.readthedocs.io/en/stable/#) as an alternative to Boost.Python for our Python bindings.

The reason I'm bringing this up is in the context of supporting Python 3 (#1782). Boost.Python is a compiled library, and it must be compiled with a particular version of Python. So to support Python 3 for our bindings, we would either have to compile Boost (or at least Boost.Python) from source, or switch to Pybind11 which is header-only and works fine with Py2 and Py3 in my tests.

I gave Pybind11 a try and particularly like that it is pretty much a drop-in replacement for Boost.Python (the syntax is nearly the same) but is more feature-rich. For instance, I was able to just delete all of our `Numpy.hpp` hacks because Pybind11 supports the Python buffer protocol that allows converting between our data types and numpy arrays (without copying). Another useful feature is automatic vectorization of C++ functions that take a `double`, to Python functions that work on numpy arrays. I have so far not found anything that Boost.Python can do but Pybind11 can't. So the only drawback I see right now is that it is a separate dependency. However, since Boost.Python is not trivial to install for Py3, it may even be easier to depend on Pybind11.

### Component:

- [ ] Code
- [ ] Documentation
- [x] Build system
- [ ] Continuous integration

### LINKED ISSUE #1839: Python binding tests are missing ctest labels
They do not, for example, show up in the summary at the end of a ctest run under "python".

### LINKED ISSUE #1923: Python bindings don't link on macOS due to unsupported --whole-archive flag
# Bug reports:

The `--whole-archive` linker flag is unsupported on macOS. It is used in the `SPECTRE_LINK_PYBINDINGS` variable in CMake, so the Pybindings don't link correctly.

### PR DESCRIPTION
**Pull request by nilsvu**
## Proposed changes

To support both Python2 and Python3 I found it easier to ditch boost.python and switch to [pybind11](https://pybind11.readthedocs.io/en/stable/) (see https://github.com/sxs-collaboration/spectre/issues/1829 for a brief comparison). By doing so this PR accomplishes the following:

- Python 2 and Python 3 support for our bindings by selecting the `PYTHON_EXECUTABLE` in CMake. Since pybind11 is header-only, there is no need to compile different versions of boost.
- Closes #1518.
- The bindings compile on macOS. Closes #1923.
- Our CI tests the bindings with Py2 and Py3.
- We can make our data structures compatible with Numpy arrays now. This PR includes a few examples (I can factor them into separate PRs if the reviewers prefer):
  - `DataVector` and `Matrix` can be converted to and from Numpy arrays (with and without copying).
  - Functions that take and return `double`s can be made to work with Numpy arrays using `py::vectorize`.
- [ ] Closes #1839. (@wthrowe please confirm)
- Closes #1829.

### Types of changes:

- [ ] Bugfix
- [x] New feature
- [ ] Refactor

### Component:

- [x] Code
- [ ] Documentation
- [x] Build system
- [x] Continuous integration

### Code review checklist

- [ ] The PR passes all checks, including unit tests and `clang-tidy`.
  For instructions on how to perform the CI checks locally refer to the [Dev
  guide on the Travis CI](https://spectre-code.org/travis_guide.html).
- [ ] The code is documented and the documentation renders correctly. Run
  `make doc` to generate the documentation locally into `BUILD_DIR/docs/html`.
  Then open `index.html`.
- [ ] The code follows the stylistic and code quality guidelines listed in the
  [code review guide](https://spectre-code.org/code_review_guide.html).

### CODE REVIEW

**Comment by moxcodes** [comment]
I think it's worth discussing our stance regarding this feature and the impending python 2 end of life. Thoughts?

**Comment by nilsvu** [comment]
Yes we should discuss that. Before this PR, everything was tested on Py2. We could either switch to Py3 exclusively, or test on both Py2 and Py3. I think supporting both can help on older clusters.

**Comment by nilsdeppe** [comment]
Unfortunately I don't think it'll be possible to require python 3 for another several years. The reason being is we realistically need to support supercomputers that are up to about 5 years old. Getting a working python installation is rather difficult and so I think we need to be flexible still for the next few years to be on the safe side. It'll be easier to maintain support for both 2 & 3 than have to add support for 2 in a few years if we get thrown onto a machine that doesn't have 3. That's my concern and opinion :man_shrugging:

**Comment by moxcodes** [comment]
Okay, I think that's pretty convincing. I do think that there will tend to be a point where it's worth dropping support for older compilers and interpreters, because until we do, we don't get to access to the full features of newer versions and 'end of life' seems on the surface a good time to discuss it. But my understanding of scientific computing realities is in agreement with what you're saying, that it is unlikely that every package and cluster is going to make the upgrade to python 3 in the next two months...

File: src/DataStructures/Python/Numpy.hpp [hunk 1]
```diff
@@ -6,9 +6,20 @@
...
 // Code is clean against Numpy 1.7.  See
 // https://docs.scipy.org/doc/numpy-1.15.1/reference/c-api.deprecations.html
 #define NPY_NO_DEPRECATED_API NPY_1_7_API_VERSION
+
+// Define this macro before including this file in the `Bindings.cpp`
+// so you can call `spectre_numpy_import_array()` when setting up the module.
+#ifdef SPECTRE_NUMPY_IMPORT_ARRAY
+#include <numpy/arrayobject.h>
+#include "PythonBindings/NumpyImportArrayWrapper.hpp"
+#else
```
Comment (kidder) [inline src/DataStructures/Python/Numpy.hpp]: add `// SPECTRE_NUMPY_IMPORT_ARRAY` to `else` and `endif` statements as it helps readability

File: src/PythonBindings/NumpyImportArrayWrapper.hpp [hunk 2]
```diff
@@ -0,0 +1,20 @@
...
+// See `DataStructures/Python/Numpy.hpp` for an example.
+#if PY_MAJOR_VERSION >= 3
+std::nullptr_t
+#else
+void
+#endif
+spectre_numpy_import_array() {
+  import_array();
+#if PY_MAJOR_VERSION >= 3
+  return nullptr;
```
Comment (kidder) [inline src/PythonBindings/NumpyImportArrayWrapper.hpp]: can you always return `nullptr` ?

File: tests/Unit/Pypp/SetupLocalPythonEnvironment.cpp [hunk 3]
```diff
@@ -15,6 +15,9 @@
 #include <numpy/arrayobject.h>  // IWYU pragma: keep
 #include <pydebug.h>
 
+// Must include this after `numpy/arrayobject.h`
+#include "PythonBindings/NumpyImportArrayWrapper.hpp"
```
Comment (kidder) [inline tests/Unit/Pypp/SetupLocalPythonEnvironment.cpp]: inline comment and group below with other includes

File: CMakeLists.txt [hunk 4]
```diff
@@ -12,6 +12,16 @@ site_name(HOSTNAME)
 
 list(APPEND CMAKE_MODULE_PATH "${CMAKE_SOURCE_DIR}/cmake")
 
+# First search for Python3 then fall back to Python2, since specifying
```
Comment (kidder) [inline CMakeLists.txt]: put this in `cmake/SetupPython.cmake`  and also change `SpectreSetupPython` to `SetupSpectrePythonPackage`

File: containers/Dockerfile.buildenv [hunk 5]
```diff
@@ -23,6 +23,12 @@ RUN apt-get update -y \
     && apt-get install -y software-properties-common \
     && add-apt-repository ppa:ubuntu-toolchain-r/test
 
+# Add Kitware repo for cmake
```
Comment (kidder) [inline containers/Dockerfile.buildenv]: let's just divide python2 and python3 tests into separate Travis build targets and only test a single one as we need to make sure the boost python module is consistent with the spectre ones

**Review by kidder — CHANGES_REQUESTED** [review]

**Comment by nilsdeppe** [comment]
@moxcodes yes, I agree. This issue somewhat tracks systems we're using and what they offer for compiler support: https://github.com/sxs-collaboration/spectre/issues/442 We could have an issue (or add to that table) python version support and then once everything is safely moved over to python3 we can remove python2 support. What do you think?

**Comment by moxcodes** [comment]
@nilsdeppe I think that's a good suggestion, to have another column indicating python version support.

**Comment by nilsvu** [comment]
@kidder @nilsdeppe @moxcodes This PR is now ready to review! I pushed a lot of small commits, but delete more code than I'm adding :)

@nilsdeppe could you take a look at the Dockerfile and update the container if you're happy with the changes? I suggest we keep boost.python in the container for a while before removing it :)

File: CMakeLists.txt [hunk 6]
```diff
@@ -72,7 +72,7 @@ include(SetupLibsharp)
 include(SetupYamlCpp)
 
 include(SetupLIBCXXCharm)
-include(SpectreSetupPython)
+include(SetupSpectrePythonPackage)
```
Comment (nilsdeppe) [inline CMakeLists.txt]: Please don't do this rename

File: containers/Dockerfile.buildenv [hunk 7]
```diff
@@ -65,11 +65,14 @@ RUN apt-get update -y \
...
+# We only install packages that are needed by the build system (e.g. to compile
+# Python bindings or build documentation) or used by Python code that is
+# unit-tested. Any other packages can be installed on-demand.
 RUN apt-get install -y python-pip python3-pip \
-    && pip3 install numpy scipy \
-    && pip install autopep8 flake8 \
-    && pip install numpy scipy matplotlib pandas h5py jupyterlab \
-    && pip install coverxygen beautifulsoup4 pybtex
+    && pip2 install numpy scipy h5py yapf \
+    && pip3 install numpy scipy h5py yapf \
```
Comment (nilsdeppe) [inline containers/Dockerfile.buildenv]: I don't think we need all of these, only h5py

File: containers/Dockerfile.buildenv [hunk 8]
```diff
@@ -101,6 +101,11 @@ RUN wget https://bitbucket.org/blaze-lib/blaze/downloads/blaze-3.2.tar.gz -O bla
     && rm -rf brigand \
     && wget https://github.com/catchorg/Catch2/releases/download/v2.2.1/catch.hpp -O catch.hpp \
     && mv catch.hpp /usr/local/include \
+    && git clone https://github.com/pybind/pybind11.git \
+    && cd pybind11 && mkdir build && cd build \
+    && cmake -D PYBIND11_TEST=OFF .. && make install \
```
Comment (nilsdeppe) [inline containers/Dockerfile.buildenv]: I don't like this install. If we can't just move the include directory to the desired location we can't really use pybind11... Furthermore, this should use a release.

File: src/DataStructures/Python/Bindings.cpp [hunk 9]
```diff
@@ -1,35 +1,16 @@
...
-// We do not use the antipattern:
-// #define NO_IMPORT_ARRAY
-// #include "DataStructures/Python/Numpy.hpp"
-// because
-// 1. This means we are controlling code in the header file with a
-//    local macro, which can be very confusing and should generally be avoided.
-// 2. When C++ modules land this type of pattern will no longer really be
-//    possible since it goes against exactly what modules is trying to do: make
-//    things modular.
+namespace py = pybind11;
```
Comment (nilsdeppe) [inline src/DataStructures/Python/Bindings.cpp:6]: please use the `bp` alias instead

**Review by nilsdeppe — CHANGES_REQUESTED** [review]
I can't review this until you make the commits easier to review. For example, the convert DataStructures commit makes a whole host of changes that make it annoying to review.

File: CMakeLists.txt (hunk 6 above)
Comment (nilsvu) [reply CMakeLists.txt]: agreed on `SpectreSetupPythonPackage` in a call

File: containers/Dockerfile.buildenv (hunk 7 above)
Comment (nilsleiffischer) [reply containers/Dockerfile.buildenv]: note from call: add comment for reasoning

Comment (nilsvu) [reply containers/Dockerfile.buildenv]: note from call: add comment for reasoning

File: containers/Dockerfile.buildenv (hunk 8 above)
Comment (nilsvu) [reply containers/Dockerfile.buildenv]: note from call: copy pybind11 cmake tools into `external` so we only need to `mv` the `include` directory

File: src/DataStructures/Python/DataVector.cpp [hunk 10]
```diff
@@ -27,6 +27,41 @@ void bind_datavector(py::module& m) {
...
+             py::buffer_info info = buffer.request();
+             // Sanity-check the buffer
+             if (info.format != py::format_descriptor<double>::format()) {
+               throw std::runtime_error(
+                   "Incompatible format: expected a double array.");
+             }
+             if (info.ndim != 1) {
+               throw std::runtime_error("Incompatible dimension.");
+             }
+            const size_t size = static_cast<size_t>(info.shape[0]);
```
Comment (nilsdeppe) [inline src/DataStructures/Python/DataVector.cpp]: Format this?

File: src/DataStructures/Python/Matrix.cpp [hunk 11]
```diff
@@ -20,8 +20,38 @@ namespace py_bindings {
```
Comment (nilsdeppe) [inline src/DataStructures/Python/Matrix.cpp:20]: Please update commit message: DataVector -> Matrix

**Review by nilsdeppe — COMMENTED** [review]
Review over a call with @nilsleiffischer.

I'm happy for you to squash everything

File: src/DataStructures/Python/Bindings.cpp (hunk 9 above)
Comment (kidder) [reply src/DataStructures/Python/Bindings.cpp:6]: what is `bp` ?

Comment (nilsvu) [reply src/DataStructures/Python/Bindings.cpp:6]: we agreed to make this `py` in the call. `bp` was `boost::python`

**Review by kidder — CHANGES_REQUESTED** [review]
I have no requested changes other than that this is tested once it passes CI on:
- [ ] wheeler
- [ ] frontera
- [x] @kidder macbook 
- [ ] @nilsdeppe laptop
- [x] @wthrowe home desktop

**Comment by nilsvu** [comment]
Done @nilsdeppe. Please take a look at the Dockerfile and update the container if you're happy with the changes. Then you can give the new bindings a try on your machines :)

Edit: These are the two relevant commits that update the Dockerfile: 0ee1726a0cc34d8cd9791054764440192d5b4001 and eb2d23e3cc559e5e958c298a85bb1efff9bdbaa5

File: containers/Dockerfile.buildenv [hunk 12]
```diff
@@ -101,10 +101,8 @@ RUN wget https://bitbucket.org/blaze-lib/blaze/downloads/blaze-3.2.tar.gz -O bla
     && rm -rf brigand \
     && wget https://github.com/catchorg/Catch2/releases/download/v2.2.1/catch.hpp -O catch.hpp \
     && mv catch.hpp /usr/local/include \
-    && git clone https://github.com/pybind/pybind11.git \
```
Comment (nilsdeppe) [inline containers/Dockerfile.buildenv]: I think this got squashed into the wrong commit, or you can remove the previous commit

File: tools/FileTestDefs.sh [hunk 13]
```diff
@@ -298,6 +298,10 @@ license() {
               'docs/config/header.html' \
               'docs/config/layout.xml' \
               'docs/config/MathJax.js$' \
+              'external/pybind11/tools/FindPythonLibsNew.cmake' \
```
Comment (nilsdeppe) [inline tools/FileTestDefs.sh]: Can you try if the regex `'external/*` works?

File: containers/Dockerfile.buildenv [hunk 14]
```diff
@@ -65,11 +65,14 @@ RUN apt-get update -y \
 RUN apt-get install -y ccache doxygen
 
 # Install Python packages
+# We only install packages that are needed by the build system (e.g. to compile
+# Python bindings or build documentation) or used by Python code that is
+# unit-tested. Any other packages can be installed on-demand.
```
Comment (nilsdeppe) [inline containers/Dockerfile.buildenv:70]: Could you specify that `We need coverxygen, beatifulsoup4, and pybtex for both python2 and python3 so that people can build the documentation with either python 2 or 3.`

**Review by nilsdeppe — COMMENTED** [review]
Looks good, couple minor things. Please squash :)

File: tools/FileTestDefs.sh (hunk 13 above)
Comment (nilsvu) [reply tools/FileTestDefs.sh]: looks like it does 👍

File: containers/Dockerfile.buildenv (hunk 12 above)
Comment (nilsvu) [reply containers/Dockerfile.buildenv]: yes I squashed it into the wrong commit. sorry for not catching that. should be fixed now.

**Comment by nilsdeppe** [comment]
Looks good! I'm updating the container now and I'll restart the tests once the container is pushed

File: containers/Dockerfile.buildenv [hunk 15]
```diff
@@ -108,6 +108,9 @@ RUN wget https://bitbucket.org/blaze-lib/blaze/downloads/blaze-3.2.tar.gz -O bla
     && rm -rf brigand \
     && wget https://github.com/catchorg/Catch2/releases/download/v2.2.1/catch.hpp -O catch.hpp \
     && mv catch.hpp /usr/local/include \
+    && wget https://github.com/pybind/pybind11/archive/v2.4.3.tar.gz -O pybind11.tar.gz \
+    && mv pybind11/include/pybind11 /usr/local/include \
```
Comment (nilsdeppe) [inline containers/Dockerfile.buildenv:114]: These should be:

```
    && wget https://github.com/pybind/pybind11/archive/v2.4.3.tar.gz -O pybind11.tar.gz \
    && tar xzf pybind11.tar.gz \
    && mv pybind11-2.4.3/include/pybind11 /usr/local/include \
    && rm -rf pybind11 \
```

**Review by nilsdeppe — CHANGES_REQUESTED** [review]

File: containers/Dockerfile.buildenv (hunk 15 above)
Comment (nilsvu) [reply containers/Dockerfile.buildenv:114]: 🤦‍♂️ I should have built the container to check. Doing so now

Comment (nilsdeppe) [reply containers/Dockerfile.buildenv:114]: I've pushed the updated container built with exactly the lines I posted.

**Comment by nilsdeppe** [comment]
@nilsleiffischer clang-tidy is failing

**Comment by nilsvu** [comment]
Fixed a bunch of clang-tidy issues and added `NOLINT`s for pybind11-specific clang-tidy complaints. This is passing the CI checks now, running in the updated container. @kidder @nilsdeppe @wthrowe could you do the respective tests that @kidder suggested?

**Comment by nilsdeppe** [comment]
A clean build doesn't work on my machine:
```
Test project /home/nils/SpECTRE/spectre/build_clangpy3
    Start 1056: Unit.Visualization.Python.GenerateXdmf
1/1 Test #1056: Unit.Visualization.Python.GenerateXdmf ...***Failed    0.20 sec
Traceback (most recent call last):
  File "/home/nils/SpECTRE/spectre/tests/Unit/Visualization/Python/Test_GenerateXdmf.py", line 6, in <module>
    import spectre.Informer as spectre_informer
  File "/home/nils/SpECTRE/spectre/build_clangpy3/bin/python/spectre/Informer/__init__.py", line 1, in <module>
    from ._PyInformer import *
ImportError: /home/nils/SpECTRE/spectre/build_clangpy3/lib/libInformer.so: undefined symbol: _Cmi_numpes
```
and
```
Test project /home/nils/SpECTRE/spectre/build_clangpy3
    Start 1054: Unit.AnalyticSolutions.GeneralRelativity.Python.Tov
1/1 Test #1054: Unit.AnalyticSolutions.GeneralRelativity.Python.Tov ...***Failed    0.04 sec
Traceback (most recent call last):
  File "/home/nils/SpECTRE/spectre/tests/Unit/PointwiseFunctions/AnalyticSolutions/GeneralRelativity/Python/Test_Tov.py", line 4, in <module>
    import spectre.PointwiseFunctions.AnalyticSolutions.GeneralRelativity \
  File "/home/nils/SpECTRE/spectre/build_clangpy3/bin/python/spectre/PointwiseFunctions/AnalyticSolutions/GeneralRelativity/__init__.py", line 1, in <module>
    from ._PyGeneralRelativitySolutions import *
ImportError: /home/nils/SpECTRE/spectre/build_clangpy3/lib/libSpectral.so: undefined symbol: sharp_make_gauss_geom_info
```

**Comment by wthrowe** [comment]
Works on my machine.  (One test fails, but it's unrelated: #1957.)

I'll test again once changes are made for @nilsdeppe's problem.

**Comment by wthrowe** [comment]
Also, this does not fix #1839.

**Comment by kidder** [comment]
@wthrowe can you clarify about #1839.  I find `Python` at the top of my `Label Time Summary` when I run `ctest` (not sure why it is the only label that isn't all lower-case...)

**Comment by nilsvu** [comment]
@nilsdeppe could you post the command you invoked cmake with, and which targets you built and ran? Did the other Python tests succeed, eg DataStructures and H5? If I can‘t reproduce your issue with that information, it would be helpful if you could send me more info about you environment (eg CMake cache) on slack

**Comment by wthrowe** [comment]
You're right, #1839 is fixed.  I only checked where I expected it to be alphabetically.

**Comment by nilsdeppe** [comment]
@nilsleiffischer 
```
cmake -GNinja -D CHARM_ROOT=/home/nils/SpECTRE/charm_68/multicore-linux64-clang -D CMAKE_C_COMPILER=clang -D CMAKE_CXX_COMPILER=clang++ -D ASAN=NO -D BUILD_SHARED_LIBS=ON -D DEBUG_SYMBOLS=OFF -D CMAKE_BUILD_TYPE=Debug -D BUILD_PYTHON_BINDINGS=ON ..
```

I built RunTests and test-executables. It was `Tov.Python`, `Informer.Python`, `VolumeData.python`, and `GenerateXdmf` that failed. 3 with the _Cmi_num_pes

**Comment by nilsvu** [comment]
@nilsdeppe have you tried building with static libraries? And do you know if the pybindings on current `develop` work with shared libs? I’m having trouble reproducing your issue because shared libs don’t work in the container currently (probably due to yamlcpp not installed with shared libs, I’ll try to work around that). I’m also going to try on another system such as minerva.

**Comment by nilsdeppe** [comment]
Building with static libs I no longer get the issue. I do think we need to support dynamic libs because they help reduce file size a lot.

**Comment by nilsdeppe** [comment]
Okay, it looks like the correct solution is that SpECTRE libraries that call into external libraries, e.g. HDF5, libsharp, LAPACK, BLAS, etc. need to mark those libs as INTERFACE link targets.

**Comment by nilsvu** [comment]
@nilsdeppe Agreed. The current boost.python bindings also don't link correctly with shared libs, opened #1961. Also, building with shared libs currently doesn't work in the container, so I fixed that in #1962. Then I can work on getting shared libs linked correctly with the bindings once the container supports it. Does that work for you?

@kidder could you verify on wheeler (and perhaps frontera) to complete your list in https://github.com/sxs-collaboration/spectre/pull/1782#pullrequestreview-349740503?

**Comment by nilsdeppe** [comment]
@nilsleiffischer sure, sounds good to me.

**Comment by nilsdeppe** [comment]
On wheeler with Clang I get:
```
8/9 Test #1056: Unit.AnalyticSolutions.GeneralRelativity.Python.Tov ...***Failed    0.30 sec
Traceback (most recent call last):
  File "/home/nils/spectre_nils/tests/Unit/PointwiseFunctions/AnalyticSolutions/GeneralRelativity/Python/Test_Tov.py", line 4, in <module>
    import spectre.PointwiseFunctions.AnalyticSolutions.GeneralRelativity \
  File "/home/nils/spectre_nils/build_clang/bin/python/spectre/PointwiseFunctions/AnalyticSolutions/GeneralRelativity/__init__.py", line 1, in <module>
    from ._PyGeneralRelativitySolutions import *
ImportError: /home/nils/spectre_nils/build_clang/bin/python/spectre/PointwiseFunctions/AnalyticSolutions/GeneralRelativity/_PyGeneralRelativitySolutions.so: undefined symbol: _ZTVN10__cxxabiv120__si_class_type_infoE
```

With GCC things work fine.

Can you add module load/unloads to the Wheeler envs for pybind11/2.4.3?

**Comment by nilsvu** [comment]
@nilsdeppe done

**Comment by nilsdeppe** [comment]
I think the correct solution is:

```
index 5b813ce..0658693 100644
--- a/cmake/SpectreSetupPythonPackage.cmake
+++ b/cmake/SpectreSetupPythonPackage.cmake
@@ -114,6 +114,11 @@ function(SPECTRE_PYTHON_ADD_MODULE MODULE_NAME)
       LIBRARY_OUTPUT_NAME "_${ARG_LIBRARY_NAME}"
       LIBRARY_OUTPUT_DIRECTORY ${MODULE_LOCATION}
       )
+    set_target_properties(
+      ${ARG_LIBRARY_NAME}
+      PROPERTIES
+      LINK_FLAGS ${CMAKE_CXX_LINK_FLAGS}
+      )
     set(SPECTRE_PYTHON_MODULE_IMPORT "from ._${ARG_LIBRARY_NAME} import *")
     add_dependencies(test-executables ${ARG_LIBRARY_NAME})
   endif(BUILD_PYTHON_BINDINGS AND NOT "${ARG_SOURCES}" STREQUAL "")
```

and then have `-lstdc++` specified in the `wheeler_clang.sh` as the `CMAKE_CXX_LINK_FLAGS`

**Comment by nilsvu** [comment]
Thanks @nilsdeppe. Could you try again on wheeler when you get the chance? I don't have an account yet.

**Comment by kidder** [comment]
works on all my machines; we haven't even tried compiling develop on frontera yet so we'll not hold up this PR for testing there...

**Review by kidder — DISMISSED** [review]

**Review by nilsdeppe — COMMENTED** [review]
Okay, this works on Wheeler now. :+1:

@wthrowe could you double check this on your machine please? Thanks!

**Review by nilsdeppe — DISMISSED** [review]

**Comment by nilsvu** [comment]
Fixed an issue with commit metadata not showing up on GitHub (I had messed up my `user.email` gitconfig) and rebased to make sure the CI runs again on current develop.

@wthrowe please test on your machine when you get the chance. thanks for reviewing @nilsdeppe @kidder @wthrowe !

**Review by kidder — APPROVED** [review]

**Comment by wthrowe** [comment]
Works for me.  (Except for #1957.)

**Review by nilsdeppe — APPROVED** [review]
